### ISSUE TITLE
Кыска+Узун+Кыска

### ISSUE THREAD

**Issue by Aykutkonushbaev** [BupycHuk/manastest#12]
эки сап(string), a жана b, берилет. Жоопко(output) жаңы сап чыгарыңыз. Кыска+узун+кыска түрүндө чыгаруу зарыл. Саптардын узундуктары бирдей болбойт, бирок бош(length 0) болушу мүмкүн.

comboString("salam", "AS") → "ASsalamAS"
comboString("ni", "POPO") → "niPOPOni"
comboString("aaa", "b") → "baaab"

**Comment by BupycHuk** [comment]
@AkimBolushbek, тапшырманы push кылганча жапса болбойт

**Comment by AkimBolushbek** [comment]
Alingan tapshirmani kantip push kilabiz?

**Comment by BupycHuk** [comment]
@AkimBolushbek,
git add .
git commit -m "fixed #12"
git push origin master

**Comment by BupycHuk** [comment]
Тикетти чечкеңге чейин жаппагыла
