### ISSUE TITLE
"6" деген сан жонундо

### ISSUE THREAD

**Issue by Aykutkonushbaev** [BupycHuk/manastest#13]
"6" абдан сыйкырдуу сан. Сизге эки сан(integer) берилет. Эгер эки сандын жок дегенде бироосу 6 болсо же экоонун айрымасы 6га барабар болсо, анда LOVE сабын(String) чыгарын. Башка учурларда NOLOVE чыгарын.

Кошумча маалымат: java тилинде Math.abs( сан ) функциясы сандын абсолютун эсептейт.

**Comment by BupycHuk** [comment]
@Tynchtykbek, Тикетти чечмейинче жаппагын

**Comment by BupycHuk** [comment]
коммиттин коментарийинде fixed #13 чогуу жазып койупсуң, ошол үчүн көрбөй калыпмын
