### ISSUE TITLE
Сүйөт же сүйбөйт

### ISSUE THREAD

**Issue by Aykutkonushbaev** [BupycHuk/manastest#16]
lovegramma функциясына сандардын тизмеси(array) берилет. Эгер тизмеде 6 же 9 сандары бар болсо, анда функция сап(String) түрүндө "LOVE" жообун кайтарышы керек(return). Андай сандар жок болсо "NoLove" сабын кайтарат.

Өрнөк:
lovegramma ({5, 11, 6, 7}) → "LOVE"
lovegramma ({1, 2, 3, 4, 5}) → "NoLove"

**Comment by AkimBolushbek** [comment]
Канча сан киргизуу керек?

**Comment by Aykutkonushbaev** [comment]
каалаганча))

**Comment by AkimBolushbek** [comment]
Мындай кылсан эч ким массивге 6 жана 9 ду кошпойт. Ошондуктан массивде белгисиз (Random) сандар болушу керек.
