### ISSUE TITLE
Саптарга мисал

### ISSUE THREAD

**Issue by AkimBolushbek** [BupycHuk/manastest#17]
Сап(string) киргизилет. Сапта бир канча соз болушу мумкун. Cоздордун арасы ","(утур) менен ажыратылат акыркы создон кийин "."(чекит) койулат.  Бул создорогу бут ундуу тамгаларды алфавиттеги катары бойунча чыгаргыла. 

Ундуу тамгалар: a, o, u, i, e.

Input                 Explore,gist,blog,help.
Output              Eeeio

**Comment by Aykutkonushbaev** [comment]
Программистерде Алфавит эмес, АлфаБит болот экен.

**Comment by BupycHuk** [comment]
@adik93 Реализациясы жакты. Бирок тапшырманы толук чечпейт. Тапшырмада акыркы создон кийин "."(чекит) койулат деп турат. Сенин чечимиңде ушул нерсеге текшерүү жок экен.

**Comment by adik93** [comment]
ондоп коемун
