### ISSUE TITLE
Массив

### ISSUE THREAD

**Issue by Aykerim** [BupycHuk/manastest#29]
Эки массив киргизилет.Алардын скалярдык көбөйтүндүсүн табуу.Мисалы: Бул массивдердин  1 3 4 6 7 жана  6 1 7 3 4 скалярдык көбөйтүндүсү  6+3+28+18+28=83.

**Comment by BupycHuk** [comment]
@AkimBolushbek эмнеге жаптың тикетти?

**Comment by AkimBolushbek** [comment]
Azyr chigaram

**Comment by BupycHuk** [comment]
@AkimBolushbek чыгармайынча жаппа, Иманалыга тандалыптыр го. Демек Иманалы чыгарат

**Comment by AkimBolushbek** [comment]
Al jagin karabaptirmin
