### ISSUE TITLE
Учурдагы датаны жана убакытты чыгаруу

### ISSUE THREAD

**Issue by AlmazTairov** [BupycHuk/manastest#30]
учурдагы датаны жана убакытты чыгаргыла. Чыгыш: "Current date is  "+day+"/"+(month+1)+"/"+year "  жана  "Current time is  "+hour+" : "+minute+" : "+second" форматында болсун

**Comment by BupycHuk** [comment]
Формат туура эмес чыгарылып жатат.
Чыгыш: "Current date is "+day+"/"+(month+1)+"/"+year " жана "Current time is "+hour+" : "+minute+" : "+second" форматында болсун
